pipeline {
    agent any
    environment {
	VERSION = '$GIT_COMMIT'
    }
    
    stages {
        stage('Source') {
            steps {
		echo "Cleaning workspace"
		sh 'rm -rf workspaces/*'
                echo 'Source step..'
		echo "Clonning my git repository"
		sh 'git clone https://github.com/sherifkunch/NV_demo.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
		echo "Start building"
		echo "Authenticating..."
		sh 'aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 855051130134.dkr.ecr.eu-central-1.amazonaws.com'
		echo "Building..." 
		sh 'docker build -t "nv-project-ecr-repository:$GIT_COMMIT" .'
		echo "Build successfully"

		echo "Tagging"
		sh 'docker tag nv-project-ecr-repository:$GIT_COMMIT 855051130134.dkr.ecr.eu-central-1.amazonaws.com/nv-project-ecr-repository:$GIT_COMMIT'

		echo "push to ECR repository"		
		echo "Docker pushing..."
		sh 'docker push 855051130134.dkr.ecr.eu-central-1.amazonaws.com/nv-project-ecr-repository:$GIT_COMMIT'
		echo "Code was uploaded successfully"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
		echo "Uploading script"
		sh 'apt install python3-pip' 
		sh 'pip3 install boto3'
		sh 'python3 Application/upload_html.py'
            }
        }
    }
}
